language: swift
osx_image: xcode12
env:
  - PROJECT_NAME=Epic

before_install:
- gem install xcpretty

install: (cd $PROJECT_NAME && swift package update)

script:
  - swiftlint
  - (cd $PROJECT_NAME && swift build)
  - (cd $PROJECT_NAME && swift test)